// Error
export const GET_ERRORS = 'GET_ERRORS';
// Work
export const GET_WORK_DATA = 'GET_WORK_DATA';
export const GET_WORK_SKILLS = 'GET_WORK_SKILLS';
export const GET_WORK_EXPERIENCE = 'GET_WORK_EXPERIENCE';
export const GET_WORK_CERTIFICATES = 'GET_WORK_CERTIFICATES';
// Author
export const GET_AUTHOR_DATA = 'GET_AUTHOR_DATA';
